[harvest]
sources = [ "githublab", "cff", "codemeta",]

[deposit]
target = "invenio_rdm"

[deposit.invenio_rdm]
site_url = "https://zenodo.org"
communities = []
access_right = "open"
record_id = 13221384

[deposit.invenio_rdm.api_paths]
depositions = "api/deposit/depositions"
licenses = "api/vocabularies/licenses"
communities = "api/communities"
