version: '2'
services:
  meta_tool:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: meta_tool
    container_name: meta_tool
    restart: unless-stopped
    env_file:
      - ./.envs/.production/.django
    expose:
      - 80
    volumes:
    - ./config:/config
    command: /start
    networks:
    - caddy_network

networks:
  caddy_network:
    external:
      name: docker_caddy_network
    
