version: '2'
services:
  meta_tool:
    build:
      context: .
      dockerfile: Dockerfile
    image: meta_tool
    container_name: meta_tool
    restart: unless-stopped
    env_file:
      - ./.envs/.production/.django
    expose:
      - 80
    volumes:
    - ./config:/config
