# Maps ConnOSS UI tabs to the software metadata properties displayed within each tab.
CONNOSS_TABS = {
    "Core Software Identity": [
        "name",
        "alternateName",
        "description",
        "identifier",
        "softwareVersion",
        "url",
        "sameAs",
        "keywords",
    ],
    "Source Code & Repository": [
        "codeRepository",
        "hasSourceCode",
        "isSourceCodeOf",
        "archivedAt",
    ],
    "Distribution & Packaging": [
        "downloadUrl",
        "installUrl",
        "softwareContainer",
    ],
    "Authors, Contributors & Maintenance": [
        "author",
        "contributor",
    ],
    "Development, Project Status & Management": [
        "buildInstructions",
        "continuousIntegration",
        "developmentStatus",
        "issueTracker",
        "releaseNotes",
        "dateCreated",
        "dateModified",
        "datePublished",
        "embargoEndDate",
        "latestRelease",
        "latestReleaseVersion",
        "partOfCommunity",
    ],
    "Technical Requirements & Environment": [
        "programmingLanguage",
        "runtimePlatform",
        "operatingSystem",
        "softwareRequirements",
        "processorRequirements",
        "memoryRequirements",
        "storageRequirements",
        "permissions",
        "availableOnDevice",
        "supportingData",
        "softwareInterface",
        "testedWith",
        "input",
        "output",
    ],
    "Software Classification & Type": [
        "applicationCategory",
        "applicationSubCategory",
        "applicationSuite",
        "targetProduct",
        "featureList",
        "softwareAddOn",
        "hasPart",
        "isPartOf",
        "relatedSoftware",
    ],
    "Documentation, Help & Support": [
        "softwareHelp",
        "readme",
        "documentation",
        "developerDocumentation",
        "userDocumentation",
        "relatedLink",
        "screenshot",
    ],
    "Publication & Citation": [
        "citation",
        "referencePublication",
        "license",
    ],
    "Others": [
        "countriesNotSupported",
        "countriesSupported",
        "isAccessibleForFree",
        "intendedUse",
        "applicationDomain",
        "legalConsiderations",
        "ethicalSocialConsiderations",
        "conditionsOfAccess",
        "implementsSpecification",
        "creditText",
        "publisher",
        "funder",
        "contactPoint",
        "copyrightHolder",
        "copyrightYear",
    ]
}

# Maps each ConnOSS software metadata property to its corresponding UI field type.
CONNOSS_FIELD_TYPES = {
    "name": "text",
    "alternateName": "tagging",
    "description": "textarea",
    "identifier": "tagging",
    "softwareVersion": "text",
    "url": "tagging",
    "sameAs": "tagging",
    "keywords": "tagging",

    "codeRepository": "text",
    "hasSourceCode": "tagging",
    "isSourceCodeOf": "tagging",
    "archivedAt": "tagging",

    "downloadUrl": "tagging",
    "installUrl": "tagging",
    "softwareContainer": "text",

    "author": "people_table",
    "contributor": "people_table_member",
    "publisher": "object_single",
    "funder": "text",
    "copyrightHolder": "text",
    "copyrightYear": "text",
    "contactPoint": "object_single",

    "buildInstructions": "tagging",
    "continuousIntegration": "text",
    "developmentStatus": "development_status",
    "issueTracker": "tagging",
    "releaseNotes": "text",
    "dateCreated": "date",
    "dateModified": "date",
    "datePublished": "date",
    "embargoEndDate": "date",
    "latestRelease": "text",
    "latestReleaseVersion": "text",
    "partOfCommunity": "text",

    "programmingLanguage": "tagging_autocomplete",
    "runtimePlatform": "tagging",
    "operatingSystem": "tagging",
    "softwareRequirements": "tagging",
    "processorRequirements": "tagging",
    "memoryRequirements": "text",
    "storageRequirements": "text",
    "permissions": "tagging",
    "availableOnDevice": "tagging",
    "supportingData": "tagging",
    "softwareInterface": "tagging",
    "testedWith": "tagging",
    "input": "text",
    "output": "text",

    "applicationCategory": "tagging",
    "applicationSubCategory": "tagging",
    "applicationSuite": "tagging",
    "targetProduct": "tagging",
    "featureList": "tagging",
    "softwareAddOn": "tagging",
    "hasPart": "tagging",
    "isPartOf": "tagging",
    "relatedSoftware": "tagging",

    "softwareHelp": "tagging",
    "readme": "tagging",
    "documentation": "tagging",
    "developerDocumentation": "tagging",
    "userDocumentation": "tagging",
    "relatedLink": "tagging",
    "screenshot": "tagging",

    "citation": "tagging",
    "referencePublication": "tagging",
    "license": "license_tagging",

    "countriesNotSupported": "tagging",
    "countriesSupported": "tagging",
    "isAccessibleForFree": "text",
    "intendedUse": "textarea",
    "applicationDomain": "tagging",
    "legalConsiderations": "text",
    "ethicalSocialConsiderations": "text",
    "conditionsOfAccess": "tagging",
    "implementsSpecification": "text",
    "creditText": "tagging"
}

# property descriptions for the ConnOSS metadata properties, used in the curation form to provide guidance to users.
CONNOSS_DESCRIPTIONS = {
  "codeRepository": "Link to the version control system where the software is developed and maintained (e.g. SVN, GitHub, CodePlex, institutional GitLab instance, etc.).",
  "codeSampleType": "The classification of the provided source code sample, indicating its completeness, execution readiness, and intended use case.\nExpected Values: full solution (or compile ready / executable), code snippet, inline code, script, template.",
  "programmingLanguage": "The computer programming languages used to develop the software.",
  "runtimePlatform": "The execution environment required to run the software, including script interpreters (e.g., Python 3.9), virtual machines (e.g., Java Virtual Machine v17), and managed frameworks (e.g., .NET Core 6.0).",
  "targetProduct": "The specific operating system, platform, or parent software application to which the code or software applies, indicating compatibility or a target ecosystem (e.g., Linux, Windows 11, WordPress, MATLAB). If the software is compatible across multiple versions, the general product name can be used alone.",
  "applicationCategory": "The high-level functional classification of the software application, indicating its primary computational purpose or technical utility (e.g., Simulation, Data Visualization, Statistical Analysis)",
  "applicationSubCategory": "A more granular technical or computational classification of the software (e.g., Agent-Based Modeling as a subcategory of Simulation & Modeling).",
  "applicationSuite": "The name of the overarching software suite, distribution, or cohesive ecosystem to which the individual software application belongs.",
  "availableOnDevice": "The specific hardware device, architecture, or machine model required to execute the software. This property is used when the software depends on specialized physical machinery, processors, or laboratory equipment.",
  "countriesNotSupported": "The list of countries where the software application is not supported, cannot be legally distributed, or is technically restricted from operating.",
  "countriesSupported": "The list of countries where the software application is explicitly supported, verified to work, or legally allowed for distribution.",
  "downloadUrl": "The direct URL from which the software binary, compiled package, executable, or compressed distribution archive (e.g., .tar.gz, .whl, .exe, .dmg) can be downloaded.",
  "featureList": "A list of the core functionalities or modules provided by the software, including components that external pipelines or applications can depend upon.",
  "fileSize": "Size of the application / package (e.g. 18MB). In the absence of a unit (MB, KB etc.), KB will be assumed.",
  "installUrl": "URL at which the app can be downloaded, including the installation instructions.",
  "memoryRequirements": "The minimum amount of Random Access Memory (RAM) required to run the software.",
  "operatingSystem": "The operating system(s) the software can be executed on (e.g. Windows 7, OSX 10.6, Android 1.6).",
  "permissions": "The explicit security privileges, access rights, or network authorizations required by the software to execute its functions successfully.",
  "processorRequirements": "could apply both to cpu and gpu",
  "releaseNotes": "Description of what changed in this version.",
  "screenshot": "A URL pointing to an image demonstrating the software's user interface, command-line execution, or visualization.",
  "softwareAddOn": "A software application, plugin, extension, or module that extends the functionality of the primary application.",
  "softwareHelp": "User guides, manuals, wikis, or help center pages that assist users in configuring and operating the software.",
  "softwareRequirements": "External software components, libraries, or packages required for the application to function.",
  "softwareVersion": "Version of the software instance.",
  "storageRequirements": "The minimum amount of persistent storage (disk space) required to install and execute the software.",
  "supportingData": "Reference datasets, auxiliary data streams, or data feeds that are bundled with, or required by the software.",
  "author": "The person or organization that created the software.",
  "citation": "A citation or reference to another creative work, such as another publication, web page, scholarly article, etc.",
  "contributor": "The person or organization that provided secondary contributions to the software.",
  "copyrightHolder": "The person or organization that holds the legal copyright and intellectual property rights to the software application.",
  "copyrightYear": "The year during which the claimed copyright for the software application was first asserted.",
  "dateCreated": "The date on which the software application repository or initial source code project was first created.",
  "dateModified": "The date on which the software application, source code repository, or specific release metadata was last updated.",
  "datePublished": "The date on which this specific version or release of the software application was officially made publicly available.",
  "encodingFormat": "The media type or serialization format used to represent the software application or its associated packages.",
  "funder": "A person or organization that supports the development and maintenance of the software application through financial contributions, grants, or sponsorships.",
  "hasPart": "Indicates a distinct creative work or component that is contained within this software application.",
  "isAccessibleForFree": "A flag to signal that the publication is accessible for free.",
  "isPartOf": "Indicates a larger software ecosystem or overarching project that this software application is a component or integrated piece of.",
  "keywords": "Keywords, tags, or terms that describe the software application.",
  "license": "The legal license that governs the copying, modification, distribution, and execution of the software application, typically indicated by URL.",
  "publisher": "The person or organization responsible for making the software application publicly available, distributing it, or managing its official archival publication.",
  "description": "A short, clear text abstract or summary that describes what the software application does and its key features.",
  "identifier": "A unique string, URL, or token that permanently and globally identifies the software application or a specific version of it, such as ISBNs, GTIN codes, UUIDs etc.",
  "name": "The name of the software application.",
  "sameAs": "URL of a reference Web page that unambiguously indicates the item's identity. E.g. the URL of the item's Wikipedia page, Wikidata entry, or official website.",
  "url": "URL of the item.",
  "relatedLink": "A link related to this object, e.g. related web pages",
  "buildInstructions": "A link to the specific documentation, scripts, or instructions required to compile, build, or install the software application.",
  "continuousIntegration": "A link to the continuous integration (CI) service or build automation platform.",
  "developmentStatus": "A term describing the current maintenance and lifecycle status of the software application (e.g., active, inactive, suspended).",
  "embargoEndDate": "Software may be embargoed from public access until a specified date (e.g. pending publication, 1 year from publication)",
  "hasSourceCode": "Link that states where the software code is for a given software. For example a software registry may indicate that one of its software entries hasSourceCode in a GitHub repository.",
  "isSourceCodeOf": "Link that states where software application is built from a given source code. This is the reverse property of 'hasSourceCode'.",
  "issueTracker": "link to software bug reporting or issue tracking system.",
  "maintainer": "Individual responsible for maintaining the software (usually includes an email contact address)",
  "readme": "link to software Readme file",
  "referencePublication": "An academic publication related to the software.",
  "relatedSoftware": "A link to other software that is related by functionality, scientific purpose, or ecosystem context (e.g. alternative implementations, comparable tools, or complementary software). \nThis property does not imply dependency, citation, or execution requirement. It is intended to support discovery, comparison, and interoperability mapping between software artifacts.",
  "contactPoint": "A contact point for this resource.",
  "creditText": "Text that can be used to credit person(s) and/or organization(s) associated with a published Creative Work.",
  "alternateName": "An alias for the resource.",
  "intendedUse": "A concise summary of the primary objective or intended use case for the software. Distinct from general description; this focuses on 'why' the software exists and what problems it solves.",
  "applicationDomain": "The discipline, area, or research domain to which this software aligns or belongs to.",
  "legalConsiderations": "A documented concern, requirement, or consideration related to the software's design, deployment, or impact across legal and regulatory dimensions (e.g. licensing constraints, data protection, compliance requirements). Enables transparent disclosure of legal constraints and mitigation strategies.",
  "ethicalSocialConsiderations": "A documented concern, requirement, or consideration related to the software's design, deployment, or impact across ethical and social dimensions. Enables transparent disclosure of constraints and mitigation strategies.",
  "archivedAt": "A link to the archived version or archival location where the original content has been preserved (for CreativeWork, MediaReview, etc.)",
  "conditionsOfAccess": "Conditions that affect the availability of, or method(s) of access to an item. Typically used for real world items such as an ArchiveComponent held by an ArchiveOrganization.",
  "documentation": "Resources that describe the software’s installation, usage, configuration, development, and deployment intended to support users and developers in understanding and applying the software.",
  "developerDocumentation": "Documentation for developers, maintainers, and infrastructure people.",
  "userDocumentation": "Documentation for end users of the software.",
  "softwareInterface": "The interaction interfaces through which users or other software systems can access, execute, or integrate with software (e.g., CLI, GUI, WebUI, Notebook, API, Library).",
  "testedWith": "Links the software to a testing activity describing how the software is validated, including the test type, required inputs, and produced test results.",
  "implementsSpecification": "A specification that a software implements, including a standard, API or legally defined level of conformance. e.g. the HTTP standard, the OpenAPI spec, OAuth2.",
  "softwareContainer": "A container image or packaged runtime environment of the software.",
  "input": "A formal specification of the data, files, or parameters that the software accepts as input, including format, type, and whether the input is required.",
  "output": "A formal specification of the data, files, or results that the software produces, including format and type.",
  "partOfCommunity": "A (research) community, consortium, or network that this research artifact (e.g., software) is developed within or affiliated with (e.g., EOSC, NFDI).",
  "latestRelease": "Link to the latest release.",
  "latestReleaseVersion": "Version of the latest release."
}

# Lists of required, recommended, and optional properties for ConnOSS software metadata, used to guide users in providing comprehensive metadata.
CONNOSS_REQUIRED_PROPERTIES = [
    "codeRepository",
    "name",
    "description",
    "license",
    "programmingLanguage",
    "author",
    "dateCreated",
    "dateModified",
    "keywords",
]

CONNOSS_RECOMMENDED_PROPERTIES = [
    "runtimePlatform",
    "storageRequirements",
    "referencePublication",
    "applicationCategory",
    "supportingData",
    "contactPoint",
    "availableOnDevice",
    "copyrightHolder",
    "intendedUse",
    "downloadUrl",
    "datePublished",
    "applicationDomain",
    "memoryRequirements",
    "identifier",
    "documentation",
    "operatingSystem",
    "url",
    "input",
    "processorRequirements",
    "developmentStatus",
    "output",
    "releaseNotes",
    "funder",
    "partOfCommunity",
    "softwareRequirements",
    "maintainer",
    "latestRelease",
    "softwareVersion",
    "readme",
    "latestReleaseVersion"
]

CONNOSS_OPTIONAL_PROPERTIES = [
    "targetProduct",
    "funder",
    "relatedSoftware",
    "applicationSubCategory",
    "hasPart",
    "creditText",
    "applicationSuite",
    "isAccessibleForFree",
    "alternateName",
    "countriesNotSupported",
    "isPartOf",
    "legalConsiderations",
    "countriesSupported",
    "publisher",
    "ethicalSocialConsiderations",
    "featureList",
    "sameAs",
    "archivedAt",
    "installUrl",
    "relatedLink",
    "conditionsOfAccess",
    "permissions",
    "buildInstructions",
    "developerDocumentation",
    "screenshot",
    "continuousIntegration",
    "userDocumentation",
    "softwareHelp",
    "embargoEndDate",
    "softwareInterface",
    "citation",
    "hasSourceCode",
    "testedWith",
    "contributor",
    "isSourceCodeOf",
    "implementsSpecification",
    "copyrightYear",
    "issueTracker",
    "softwareContainer"
]

# Static JSON-LD context: shown and downloaded, but intentionally not editable.
CONNOSS_JSONLD_CONTEXT = {
    "linkml": "https://w3id.org/linkml/", "sdo": "https://schema.org/",
    "cm": "https://codemeta.github.io/terms/", "spdx": "https://spdx.org/licenses/",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
}
for _term in (
    "codeRepository codeSampleType programmingLanguage runtimePlatform targetProduct "
    "applicationCategory applicationSubCategory applicationSuite availableOnDevice "
    "countriesNotSupported countriesSupported downloadUrl featureList fileSize installUrl "
    "memoryRequirements operatingSystem permissions processorRequirements releaseNotes screenshot "
    "softwareAddOn softwareHelp softwareRequirements softwareVersion storageRequirements supportingData "
    "author citation contributor copyrightHolder copyrightYear dateCreated dateModified datePublished "
    "encodingFormat funder hasPart isAccessibleForFree isPartOf keywords license publisher review sponsor "
    "description identifier name sameAs url relatedLink relatedSoftware contactPoint creditText alternateName "
    "intendedUse applicationDomain legalConsiderations ethicalSocialConsiderations archivedAt conditionsOfAccess "
    "documentation softwareInterface testedWith implementsSpecification softwareContainer input output partOfCommunity "
    "latestRelease"
).split():
    CONNOSS_JSONLD_CONTEXT[_term] = f"sdo:{_term}"
for _term in (
    "buildInstructions continuousIntegration developmentStatus embargoEndDate hasSourceCode "
    "isSourceCodeOf issueTracker readme referencePublication developerDocumentation userDocumentation "
    "latestReleaseVersion"
).split():
    CONNOSS_JSONLD_CONTEXT[_term] = f"cm:{_term}"
