# Generated by Django 6.0.3 on 2026-04-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Site Stat',
                'verbose_name_plural': 'Site Stats',
                'ordering': ['-date', '-hour'],
                'unique_together': {('date', 'hour')},
            },
        ),
    ]
