name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI_PERSONAL_TOKEN_KEY_GL: ${{ secrets.CI_PERSONAL_TOKEN_KEY_GL }}
      GL_URL: ${{ vars.GL_URL }}
      CI_PERSONAL_TOKEN_KEY_GH: ${{ secrets.CI_PERSONAL_TOKEN_KEY_GH }}
      GH_URL: ${{ vars.GH_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Run server
      run: |
        source env/bin/activate
        python manage.py runserver 0.0.0.0:8000 &
      env:
        CI_PERSONAL_TOKEN_KEY_GL: ${{ secrets.CI_PERSONAL_TOKEN_KEY_GL }}
        GL_URL: ${{ vars.GL_URL }}

  test:
    runs-on: ubuntu-latest
    needs: build

    env:
      CI_PERSONAL_TOKEN_KEY_GL: ${{ secrets.CI_PERSONAL_TOKEN_KEY_GL }}
      GL_URL: ${{ vars.GL_URL }}
      CI_PERSONAL_TOKEN_KEY_GH: ${{ secrets.CI_PERSONAL_TOKEN_KEY_GH }}
      GH_URL: ${{ vars.GH_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source env/bin/activate
        echo "$GL_URL"
        echo "$GH_URL"
        python manage.py test tests
